# Generated by Django 3.0.6 on 2020-07-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsgn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Author name')),
                ('nation', models.CharField(max_length=80, unique=True, verbose_name='Nationality')),
            ],
        ),
        migrations.AddField(
            model_name='entryarticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsgn.Author'),
        ),
    ]
