# Generated by Django 3.0.6 on 2020-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsgn', '0002_auto_20200728_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(max_length=80, verbose_name='Nationality'),
        ),
    ]
