# Generated by Django 3.0.6 on 2020-07-29 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsgn', '0003_auto_20200728_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogsgn.Author')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogsgn.EntryArticle')),
            ],
        ),
    ]
