# Generated by Django 3.0.6 on 2020-07-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsgn', '0004_articlecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='Article name')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('context', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsgn.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='entryarticle',
            name='author',
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
        migrations.DeleteModel(
            name='EntryArticle',
        ),
    ]
