# Generated by Django 3.0.6 on 2020-08-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsgn', '0008_auto_20200731_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('CH', 'China'), ('US', 'America'), ('UK', 'England'), ('GE', 'German')], max_length=80, verbose_name='Nationality'),
        ),
    ]
